config/routes.rb
Rails.application.routes.draw do

  resources :work_histories
  resources :meetings
  resources :commons
  resources :cause_histories
  resources :user_web
  resources :dashboard_causes
  resources :dashboard_audiencias

  get 'calender/index'
  get 'user_web/index'
  get 'user/index'
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :works
  resources :causes
  resources :clients
  resources :attorneys
  resources :cause_statuses
  resources :work_statuses
  resources :audiences
  resources :client_works
  resources :work_json
  resources :user
  resources :calender
  resources :regions
  resources :user_datos
  resources :login
  resources :causes_abogado
  resources :work_abogado

  root 'welcome#index'
  get  'welcome/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    if user.role == "admin"

      can :manage, :all

    elsif user.role == "attorney"

    elsif user.role == "client"

  end

  end
end

app/models/attorney.rb
class Attorney < ApplicationRecord
  belongs_to :user
 
end

app/models/audience.rb
class Audience < ApplicationRecord
  belongs_to :attorney
  belongs_to :cause
end

app/models/cause.rb
class Cause < ApplicationRecord
  belongs_to :attorney
  belongs_to :client
end

app/models/cause_history.rb
class CauseHistory < ApplicationRecord
  belongs_to :attorney
  belongs_to :cause
end

app/models/cause_status.rb
class CauseStatus < ApplicationRecord
  belongs_to :cause
  belongs_to :attorney
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
end

app/models/common.rb
class Common < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :attorney
  belongs_to :work
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :client
  belongs_to :attorney
end

app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :attorney
  belongs_to :work
end

app/models/work_status.rb
class WorkStatus < ApplicationRecord
  belongs_to :work
  belongs_to :attorney
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def index
    @user = current_user.id
    @emailuser = User.find(current_user.id)
    @abogado =Attorney.where(:user_id => current_user.id)
    @usuario = User.find(current_user.id)

  end

  def update
    @user.update(user_params)
  end


  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end
end

app/helpers/apicausa_helper.rb
module ApicausaHelper
end

app/helpers/calender_helper.rb
module CalenderHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/user/index.html.erb
 <!--<div class="content-wrapper">
   
    <section class="content-header">
      <h1>
       Perfil de Usuario
      </h1>
   
    </section>

   
    <section class="content">

      <div class="row">
        <div class="col-md-6">
          <div class="box box-primary">
            <div class="box-body box-profile">
        <img class="profile-user-img img-responsive img-circle" src="../../dist/img/user4-128x128.jpg" alt="User profile picture"

              <h3 class="profile-username text-center"><%=@emailuser.email%></h3>

            <%if @emailuser.role == 'admin'%>
              <p class="text-muted text-center">Administrador</p>
            <%else%>
              <p class="text-muted text-center">Abogado</p>
            <%end%>
   
              <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Followers</b> <a class="pull-right">1,322</a>
                </li>
                <li class="list-group-item">
                  <b>Following</b> <a class="pull-right">543</a>
                </li>
                <li class="list-group-item">
                  <b>Friends</b> <a class="pull-right">13,287</a>
                </li>
              </ul>

            
            </div>
           
          </div>
          

         
        </div>
          <%if @emailuser.role == "admin"%>
      
         <div class="col-md-12">
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
           
              <li><a href="#settings" data-toggle="tab">Configuracion</a></li>
            </ul>
          
             

              <div class="tab-pane" id="settings">
                <form class="form-horizontal">
                
                  <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Email</label>

                    <div class="col-sm-8">
                      <input type="email" class="form-control" id="inputEmail" placeholder=" <%= @usuario.email %>">
                     
                    </div>
                  </div>
                
                  <div class="form-group">
                    <label for="inputExperience" class="col-sm-2 control-label">Contrasena</label>

                    <div class="col-sm-8">
                   <input type="text" class="form-control" id="inputName" placeholder="">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputSkills" class="col-sm-2 control-label">Confirmar Contrasena</label>

                    <div class="col-sm-8">
                      <input type="text" class="form-control" id="inputSkills" placeholder="">
                    </div>
                  </div>
                 
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-8">
                      <button type="submit" class="btn btn-danger">Modificar</button>
                    </div>
                  </div>
                </form>
              </div>
            
          
         
          </div>
         
        </div>
        <%else%>
        <div class="col-md-12">
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
           
              <li><a href="#settings" data-toggle="tab">Configuracion</a></li>
            </ul>
          
             
          <%@abogado.each do |attorney|%>
              <div class="tab-pane" id="settings">
                <form class="form-horizontal">
                  <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Nombre</label>
            
                    <div class="col-sm-8">
                      <input  class="form-control" id="inputName" placeholder=" <%= attorney.name %> ">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Email</label>

                    <div class="col-sm-8">
                      <input type="email" class="form-control" id="inputEmail" placeholder="<%= attorney.email %> ">
                    </div>
                  </div>
                
                  <div class="form-group">
                    <label for="inputExperience" class="col-sm-2 control-label">Contrasena</label>

                    <div class="col-sm-8">
                   <input type="text" class="form-control" id="inputName" placeholder="">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputSkills" class="col-sm-2 control-label">Confirmar Contrasena</label>

                    <div class="col-sm-8">
                      <input type="text" class="form-control" id="inputSkills" placeholder="">
                    </div>
                  </div>
                 
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-8">
                    <input class="btn btn-success" onclick="ModificarUsuario()" type="button">Modificar
                      
                    </div>

                  </div>

                  
                </form>
              </div>
            
          </div>
      
        </div>
          <%end%>
        <%end%>
       
      </div>
     

    </section>
   
  </div>-->

      <div class="col-md-3">
         <section class="content-header">
            <h6 style="margin-left:2%"> MI PERFIL
            <i class="fas fa-angle-right fa-2x" style=" float: right;color: #c4a215;margin-right: 8%;"></i>
              </h6>
          </section>
      </div>
  
       <div id="cliente" class="col-md-8" style="border-left: 1px solid black;">
          <section class="content-header-menu" >
            <h6>
            <span  id="direccionCliente" style="margin-left: 3%;">NOMBRE USUARIO</span>
           
           
             <span  style="margin-right: 3%;float: right;">RUT</span>
            </h6>
          </section>

            <section class="border-menu-2" >
              <img src="http://www.lanzaderaonline.com/wp-content/uploads/2016/08/MAL-AVATAR.jpg" class="float-left imagen-cliente">
            </section>

            <section class="content-form">
                <h6>
                  <label style="margin-left:40%">CONTACTO</label>
                  <label id="contacto" style="margin-left:5%"></label>
                </h6>
            </section>
             <section class="content-form">
                <h6>
                  <label style="margin-left:40%">NOMBRE</label>
                  <label id="contacto" style="margin-left:5%"></label>
                </h6>
            </section>
             <section class="content-form">
                <h6>
                  <label style="margin-left:40%">RUT</label>
                  <label id="contacto" style="margin-left:5%"></label>
                </h6>
            </section>
             <section class="content-form">
                <h6>
                  <label style="margin-left:40%">CARGO</label>
                  <label id="contacto" style="margin-left:5%"></label>
                </h6>
            </section>
            <section class="content-form">
                <h6>
                    <label style="margin-left:40%">TELEFONO</label>
                  <label id="telefono" style="margin-left:5%"></label>
                </h6>
            </section>
            <section class="content-form">
                <h6>
                   <label style="margin-left:40%">CORREO</label>
                  <label  id="correo" style="margin-left:5%"></label>
                </h6>
            </section>
            <section class="content-form">
                <h6>
                  <label style="margin-left:40%">DIRECCION</label>
                  <label id="direccion" style="margin-left:5%"></label>
                </h6>
            </section>
            <section class="content-form">
                <h6>
                  <label style="margin-left:40%">ESTADO CIVIL</label>
                  <label id="direccion" style="margin-left:5%"></label>
                </h6>
            </section>
            <section class="content-form">
                <h6>
                  <label style="margin-left:40%">CONTRASEÑA</label>
                  <label id="direccion" style="margin-left:5%"></label>
                </h6>
            </section>
         
        </div>
        

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>