config/routes.rb
Rails.application.routes.draw do

  resources :work_histories
  resources :meetings
  resources :commons
  resources :cause_histories
  resources :user_web
  resources :dashboard_causes
  resources :dashboard_audiencias

  get 'calender/index'
  get 'user_web/index'
  get 'user/index'
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :works
  resources :causes
  resources :clients
  resources :attorneys
  resources :cause_statuses
  resources :work_statuses
  resources :audiences
  resources :client_works
  resources :work_json
  resources :user
  resources :calender
  resources :regions
  resources :user_datos
  resources :login
  resources :causes_abogado
  resources :work_abogado

  root 'welcome#index'
  get  'welcome/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    if user.role == "admin"

      can :manage, :all

    elsif user.role == "attorney"

    elsif user.role == "client"

  end

  end
end

app/models/attorney.rb
class Attorney < ApplicationRecord
  belongs_to :user
 
end

app/models/audience.rb
class Audience < ApplicationRecord
  belongs_to :attorney
  belongs_to :cause
end

app/models/cause.rb
class Cause < ApplicationRecord
  belongs_to :attorney
  belongs_to :client
end

app/models/cause_history.rb
class CauseHistory < ApplicationRecord
  belongs_to :attorney
  belongs_to :cause
end

app/models/cause_status.rb
class CauseStatus < ApplicationRecord
  belongs_to :cause
  belongs_to :attorney
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
end

app/models/common.rb
class Common < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :attorney
  belongs_to :work
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :client
  belongs_to :attorney
end

app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :attorney
  belongs_to :work
end

app/models/work_status.rb
class WorkStatus < ApplicationRecord
  belongs_to :work
  belongs_to :attorney
end

app/controllers/api/audiences_controller.rb
class Api::AudiencesController < ApplicationController
end

app/controllers/audiences_controller.rb
class AudiencesController < ApplicationController
  before_action :set_audience, only: [:show, :edit, :update, :destroy]

  # GET /audiences
  # GET /audiences.json
  def index
    @user = current_user.id
    @emailuser = User.find(current_user.id)
    @audiences = Audience.joins(:attorney).joins(:cause)
    .pluck(
      'audiences.date',
      'audiences.attorney_id',
      'attorneys.name',
      'audiences.cause_id',
      'audiences.created_at',
      'audiences.updated_at',
      'audiences.id',
      'audiences.description',
      'audiences.finished',
      'causes.code',
      'attorneys.photo',
    )
   render json: @audiences
  end

  

  # GET /audiences/1
  # GET /audiences/1.json
  def show
    
  end


  # GET /audiences/new
  def new
    @audience = Audience.new
  end

  # GET /audiences/1/edit
  def edit
  end

  # POST /audiences
  # POST /audiences.json
  def create
    @audience = Audience.create(audience_params)
  end

  # PATCH/PUT /audiences/1
  # PATCH/PUT /audiences/1.json
  def update
    respond_to do |format|
      if @audience.update(audience_params)
        format.html { redirect_to @audience, notice: 'Attorney was successfully updated.' }
        format.json { render :show, status: :ok, location: @audience }
      else
        format.html { render :edit }
        format.json { render json: @audience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audiences/1
  # DELETE /audiences/1.json
  def destroy
    @audience.destroy
    respond_to do |format|
      format.html { redirect_to audiences_url, notice: 'Audience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audience
      @audience = Audience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audience_params
      params.require(:audience).permit(:date, :attorney_id, :cause_id, :description,:finished)
    end
end

app/helpers/apicausa_helper.rb
module ApicausaHelper
end

app/helpers/audiences_helper.rb
module AudiencesHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/audiences/_form.html.erb
<%= form_with(model: audience, local: true) do |form| %>
  <% if audience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(audience.errors.count, "error") %> prohibited this audience from being saved:</h2>

      <ul>
      <% audience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :attorney_id %>
    <%= form.text_field :attorney_id %>
  </div>

  <div class="field">
    <%= form.label :cause_id %>
    <%= form.text_field :cause_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/audiences/_new.html.erb
<div id="myModalAudiences" class="modal fade"  >
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Nueva Audiencia</h4>
      </div>

        <%= form_for @audience, remote: true do |form| %>
        <div class="modal-body">
          <!-- Main content -->
          <section class="content">
            <div class="row">
              <div class="col-md-12">
                <div class="box box-primary">
              
                  <form role="form">
                    <div class="box-body">
                    <div class="alert alert-danger" role="alert" style="display: none;"></div>
                      <div class="form-group col-md-8">
                        <%= form.label :Fecha_Audiencia %>
                        <%= form.datetime_select :date, 
                         {
                                  :order => [:day, :month, :year], 
                                  :value => DateTime.now.strftime('%m/%d/%Y')
                                }%>
                      </div>
                      
              
                      <div class="form-group col-md-4">
                        <%= form.label :Abogago_a_cargo %>
                        <%= form.select :attorney_id, options_from_collection_for_select( Attorney.all, :id, :name)  %>
                        
                      </div>

                        <div class="form-group col-md-4">
                            <%= form.label :Causa %>
                         
                             <%= form.select :cause_id, options_from_collection_for_select( Cause.all, :id, :name)  %>
                            
                         </div>


                      
                    </div>
                </div>
              </div>  <!-- /.box -->
                    <div class="modal-footer">
                        <%= form.submit "Guardar", class: "btn btn-primary btn-lg btn-block" %>
                    </div>
                  <% end %>
              </div>
              
          </div>
        </div>
      </div>

app/views/audiences/create.js.erb
<% if @audience.errors.empty? %>
$('#myModalAudiences').modal('hide');
<% else %>
  alert('<%= @cause.errors.full_messages[0] %>');
<% end %>

app/views/audiences/edit.html.erb
<h1>Editing Audience</h1>

<%= render 'form', audience: @audience %>

<%= link_to 'Show', @audience %> |
<%= link_to 'Back', audiences_path %>

app/views/audiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Audiences</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Attorney</th>
      <th>Cause</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @audiences.each do |audience| %>
      <tr>
        <td><%= audience.date %></td>
        <td><%= audience.attorney %></td>
        <td><%= audience.cause %></td>
        <td><%= link_to 'Show', audience %></td>
        <td><%= link_to 'Edit', edit_audience_path(audience) %></td>
        <td><%= link_to 'Destroy', audience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Audience', new_audience_path %>

app/views/audiences/new.html.erb
<h1>New Audience</h1>

<%= render 'form', audience: @audience %>

<%= link_to 'Back', audiences_path %>

app/views/audiences/new.js.erb
$('<%= j render "new"%>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/audiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @audience.date %>
</p>

<p>
  <strong>Attorney:</strong>
  <%= @audience.attorney %>
</p>

<p>
  <strong>Cause:</strong>
  <%= @audience.cause %>
</p>

<%= link_to 'Edit', edit_audience_path(@audience) %> |
<%= link_to 'Back', audiences_path %>