config/routes.rb
Rails.application.routes.draw do

  resources :work_histories
  resources :meetings
  resources :commons
  resources :cause_histories
  resources :user_web
  resources :dashboard_causes
  resources :dashboard_audiencias

  get 'calender/index'
  get 'user_web/index'
  get 'user/index'
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :works
  resources :causes
  resources :clients
  resources :attorneys
  resources :cause_statuses
  resources :work_statuses
  resources :audiences
  resources :client_works
  resources :work_json
  resources :user
  resources :calender
  resources :regions
  resources :user_datos
  resources :login
  resources :causes_abogado
  resources :work_abogado

  root 'welcome#index'
  get  'welcome/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    if user.role == "admin"

      can :manage, :all

    elsif user.role == "attorney"

    elsif user.role == "client"

  end

  end
end

app/models/attorney.rb
class Attorney < ApplicationRecord
  belongs_to :user
 
end

app/models/audience.rb
class Audience < ApplicationRecord
  belongs_to :attorney
  belongs_to :cause
end

app/models/cause.rb
class Cause < ApplicationRecord
  belongs_to :attorney
  belongs_to :client
end

app/models/cause_history.rb
class CauseHistory < ApplicationRecord
  belongs_to :attorney
  belongs_to :cause
end

app/models/cause_status.rb
class CauseStatus < ApplicationRecord
  belongs_to :cause
  belongs_to :attorney
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
end

app/models/common.rb
class Common < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :attorney
  belongs_to :work
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :client
  belongs_to :attorney
end

app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :attorney
  belongs_to :work
end

app/models/work_status.rb
class WorkStatus < ApplicationRecord
  belongs_to :work
  belongs_to :attorney
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @user = current_user.id
    @emailuser = User.find(current_user.id)
    @clients = Client.all.order(name: :asc)
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @user = current_user.id
    @emailuser = User.find(current_user.id)
  end

  # GET /clients/new
  def new
    @user = current_user.id
    @emailuser = User.find(current_user.id)
    @client = Client.new
    @User = User.new
  end

  # GET /clients/1/edit
  def edit
    @user = current_user.id
    @emailuser = User.find(current_user.id)
    @client = Client.all
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.create(client_params)
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: '' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name,:user_id,:plan,:kind,:region,:commune,:rut,:name_legal,:rut_legal,:mail_legal,:phone_legal,:attorney_id,:address,:option,:profession,:marital_status,:court_order)
    end

    def user_params
      params.require(:client).permit(:email, :password, :password_confirmation,:role)
    
      
    end
end

app/helpers/apicausa_helper.rb
module ApicausaHelper
end

app/helpers/calender_helper.rb
module CalenderHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/clients/index.html.erb
<!--<div class="content-wrapper">
    <section class="content-header">
      <h1>
        Clientes
        <small></small>
        
      </h1> 
    </section>

    
    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <div class="box">
           <div class="box-body table-responsive no-padding">
              <table class="table " id="table-cause" >
                <tr>
                  <th id="nombre">Nombre</th>
                 
                  <th colspan="2"></th>
                </tr>
                    <tbody id='body-cause'>
                     <% @clients.each do |client| %>
                                  <tr>
                                      <td class='btn' onclick='BuscarCliente(" <%= client.id %> ")'><%= client.name %></td>
                                      <td><%= link_to 'Editar', edit_client_path(client) %></td>
                                   
                                  </tr>
                                <% end %>
                    </tbody>
              </table>
            </div>
           
          </div>

           <%= link_to 'Nuevo Cliente', new_client_path,class:"btn btn-block btn-social btn-bitbucket" %>
            
        </div>
      
        <div class="col-md-6">
        
          <div class="box ">
            <div class="box-header with-border">
              <h3 class="box-title">Nombre Cliente</h3>
            </div>
            <form class="form-horizontal">
              <div class="box-body">
               <div style=" width: 40%; margin-left: 4%; float:left;">
                <div class="form-group">
                  <label for="inputEmail3" class="col-sm-3 control-label">Plan</label>
                    <div class="col-sm-8">
                      <input type="email" class="form-control" id="idplan" placeholder="Plan">
                    </div>
                </div>
                <div class="form-group">
                  <label for="Nombre" class="col-sm-3 control-label">Tipo</label>
                  <div class="col-sm-8">
                    <input type="Nombre" class="form-control" id="idtipo1" placeholder="Tipo">
                  </div>
                </div>
                <div class="form-group">
                  <label for="Nombre" class="col-sm-3 control-label">Region</label>

                  <div class="col-sm-8">
                    <input type="Nombre" class="form-control" id="idregion" placeholder="Region">
                  </div>
                </div>
                <div class="form-group">
                  <label for="Rol" class="col-sm-3 control-label">Comuna</label>

                  <div class="col-sm-8">
                    <input type="Rol" class="form-control" id="idcomuna" placeholder="Comuna">
                  </div>
                </div>
            
              </div>
            </form>
          </div>

          <div class="box ">
            <div class="box-header with-border">
              <h3 class="box-title">Datos Generales</h3>
            </div>
            <form class="form-horizontal">
              <div class="box-body">
               <div style=" width: 40%; margin-left: 4%; float:left;">
                <div class="form-group">
                  <label for="inputEmail3" class="col-sm-3 control-label">Cliente</label>
                    <div class="col-sm-8">
                      <input type="email" class="form-control" id="idname" placeholder="Cliente">
                    </div>
                </div>
                <div class="form-group">
                  <label for="Nombre" class="col-sm-3 control-label">Tipo</label>
                  <div class="col-sm-8">
                    <input type="Nombre" class="form-control" id="idtipo" placeholder="Tipo">
                  </div>
                </div>
                <div class="form-group">
                  <label for="Nombre" class="col-sm-3 control-label">Rut</label>

                  <div class="col-sm-8">
                    <input type="Nombre" class="form-control" id="idrut" placeholder="Rut">
                  </div>
                </div>
            
            
              </div>
            </form>
          </div>

           <div class="box ">
            <div class="box-header with-border">
              <h3 class="box-title">Representante Legal</h3>
            </div>
            <form class="form-horizontal">
              <div class="box-body">
               <div style=" width: 40%; margin-left: 4%; float:left;">
                <div class="form-group">
                  <label for="inputEmail3" class="col-sm-3 control-label">Nombre</label>
                    <div class="col-sm-8">
                      <input type="email" class="form-control" id="idnamelegal" placeholder="Nombre">
                    </div>
                </div>
                <div class="form-group">
                  <label for="Nombre" class="col-sm-3 control-label">Rut</label>
                  <div class="col-sm-8">
                    <input type="Nombre" class="form-control" id="idrutlegal" placeholder="Rut">
                  </div>
                </div>
                <div class="form-group">
                  <label for="Nombre" class="col-sm-3 control-label">Correo</label>

                  <div class="col-sm-8">
                    <input type="Nombre" class="form-control" id="idmaillegal" placeholder="Correo">
                  </div>
                </div>
                 <div class="form-group">
                  <label for="Nombre" class="col-sm-3 control-label">Telefono</label>

                  <div class="col-sm-8">
                    <input type="Nombre" class="form-control" id="idphonelegal" placeholder="Telefono">
                  </div>
                </div>
            
            
              </div>
            </form>
          </div>

        </div>

       

      </div>
    </section> 

    
      
  </div>-->


  
    
        <div class="col-md-3">
         <section class="content-header">
       <!--     <h6>
               <select style="margin-left: 2%" id="Estado">
                <option>Listado</option>
              
              </select>
              <i class="fas fa-angle-right fa-2x" style=" float: right;color: #c4a215;margin-right: 8%;"></i>
             
            </h6>-->
          </section>

             <section class="content-header">
          
            <h6><i class="fas fa-angle-right" style="margin-left: 2%; color: #c4a215;"></i>
              CLIENTES 
              
              </h6>
          </section>
          
          <!--<section class="content-header">
          
            <h6><i class="fas fa-angle-right" style="margin-left: 2%; color: #c4a215;"></i>
              CAUSAS JUDICIALES 
              
             <i> <%= link_to '', new_cause_path, :remote=>true ,class:'fas fa-plus-circle fa-2x', style:'color:#c4a215;float: right;margin-right: 6%;margin-top: -2%;' %></i>
             <label style="float: right;margin-right: 5%;">Archivo</label>
              </h6>
          </section>-->

            <div class="box-body">
              <table class="multilinia" id="table-cliente-abogado" >
                <tr>
                </tr>
                   
              </table>
            </div>
         

      <!--      <section class="content-header">
            
              <h6><i class="fas fa-angle-right" style="margin-left: 2%;  color: #c4a215;"></i>
                GESTIONES
      
              <label style="float: right;margin-right: 5%;">Archivo</label></h6>
            </section>

           <div class="box-body">
              <table  id="table-work-cliente" >
                <tr>
                </tr>
                   
              </table>
            </div>-->


              
        </div>
  
        <div id="cliente" class="col-md-8" style="border-left: 1px solid black;">
          <section class="content-header-menu" >
            <h6>
            <span  id="direccionCliente" style="margin-left: 3%;"></span>
           
            <span style="/* margin-left: 68%; */float: right;/* margin-bottom: 222222%; */margin-right: 2%;margin-top: -0.5%;"> 
           <!-- <select  id="combocliente">
            </select></span>-->
             <span  style="margin-right: 3%;float: right;"></span>
            </h6>
          </section>

            <%# <section class="border-menu-2" >
              <img src="http://www.lanzaderaonline.com/wp-content/uploads/2016/08/MAL-AVATAR.jpg" class="float-left imagen-cliente">
            </section> %>

            <section class="content-form">
                <h6>
                  <label style="margin-left:5%">NOMBRE</label>
                  <label id="nombrec_abogado" style="margin-left:5%"></label>
                </h6>
            </section>
            <section class="content-form">
                <h6>
                    <label style="margin-left:5%">RUT</label>
                  <label id="rutc_abogado" style="margin-left:5%"></label>
                </h6>
            </section>
            <%# <section class="content-form">
                <h6>
                   <label style="margin-left:40%">PLAN</label>
                  <label  id="planc_abogado" style="margin-left:5%"></label>
                </h6>
            </section> %>
           
             <section class="content-form">
                <h6>
                  <label style="margin-left:5%">REGION</label>
                  <label id="regionc_abogado" style="margin-left:5%"></label>
                </h6>
            </section>
             <%# <section class="content-form">
                <h6>
                  <label style="margin-left:40%">COMUNA</label>
                  <label id="comunac_abogado" style="margin-left:5%"></label>
                </h6>
            </section> %>
             <section class="content-form">
                <h6>
                  <label style="margin-left:5%">DIRECCION</label>
                  <label id="direccionc_abogado" style="margin-left:5%"></label>
                </h6>
            </section>
            
            <section id="menu-rl" class="content-form" style="display:none">
                <h6>
                  <label style="margin-left:5%">REPRESENTANTE LEGAL</label>
                  <label id="representantec_abogado" style="margin-left:5%"></label>
                </h6>
            </section>
            <section id="menu-rutlegal" class="content-form" style="display:none">
                <h6>
                  <label style="margin-left:5%" >RUT</label>
                  <label id="rutlegalc_abogado" style="margin-left:5%"></label>
                </h6>
            </section>
             <section class="content-form">
                <h6>
                  <label style="margin-left:5%">OFICIO</label>
                  <label id="oficioc_abogado" style="margin-left:5%"></label>
                </h6>
            </section>
            <section class="content-form">
                <h6>
                  <label style="margin-left:5%">ESTADO CIVIL</label>
                  <label id="estadoc_abogado" style="margin-left:5%"></label>
                </h6>
            </section>
        </div>

<script>
 $(document).ready(obtenerLogin_cliente);
</script>