config/routes.rb
Rails.application.routes.draw do

  resources :work_histories
  resources :meetings
  resources :commons
  resources :cause_histories
  resources :user_web
  resources :dashboard_causes
  resources :dashboard_audiencias

  get 'calender/index'
  get 'user_web/index'
  get 'user/index'
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :works
  resources :causes
  resources :clients
  resources :attorneys
  resources :cause_statuses
  resources :work_statuses
  resources :audiences
  resources :client_works
  resources :work_json
  resources :user
  resources :calender
  resources :regions
  resources :user_datos
  resources :login
  resources :causes_abogado
  resources :work_abogado

  root 'welcome#index'
  get  'welcome/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    if user.role == "admin"

      can :manage, :all

    elsif user.role == "attorney"

    elsif user.role == "client"

  end

  end
end

app/models/attorney.rb
class Attorney < ApplicationRecord
  belongs_to :user
 
end

app/models/audience.rb
class Audience < ApplicationRecord
  belongs_to :attorney
  belongs_to :cause
end

app/models/cause.rb
class Cause < ApplicationRecord
  belongs_to :attorney
  belongs_to :client
end

app/models/cause_history.rb
class CauseHistory < ApplicationRecord
  belongs_to :attorney
  belongs_to :cause
end

app/models/cause_status.rb
class CauseStatus < ApplicationRecord
  belongs_to :cause
  belongs_to :attorney
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
end

app/models/common.rb
class Common < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :attorney
  belongs_to :work
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :client
  belongs_to :attorney
end

app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :attorney
  belongs_to :work
end

app/models/work_status.rb
class WorkStatus < ApplicationRecord
  belongs_to :work
  belongs_to :attorney
end

app/controllers/cause_statuses_controller.rb
class CauseStatusesController < ApplicationController
  before_action :set_cause_status, only: [:show, :edit, :update, :destroy]

  # GET /cause_statuses
  # GET /cause_statuses.json
  def index
    @cause_statuses = CauseStatus.joins(:attorney)
    .pluck(
      'cause_statuses.description',
      'cause_statuses.expiration_date',
      'cause_statuses.attorney_id',
      'cause_statuses.id',
      'cause_statuses.finished',
      'cause_statuses.cause_id',
      'attorneys.photo'
    )
   render json: @cause_statuses


  end

  # GET /cause_statuses/1
  # GET /cause_statuses/1.json
  def show
  end

  # GET /cause_statuses/new
  def new
    @cause_status = CauseStatus.new
  end

  # GET /cause_statuses/1/edit
  def edit
  end

  # POST /cause_statuses
  # POST /cause_statuses.json
  def create
    @cause_status = CauseStatus.create(cause_status_params)
  end

  # PATCH/PUT /cause_statuses/1
  # PATCH/PUT /cause_statuses/1.json
  def update
    respond_to do |format|
      if @cause_status.update(cause_status_params)
        format.html { redirect_to @cause_status, notice: 'Audience was successfully updated.' }
        format.json { render :show, status: :ok, location: @cause_status }
      else
        format.html { render :edit }
        format.json { render json: @cause_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cause_statuses/1
  # DELETE /cause_statuses/1.json
  def destroy
    @cause_status.destroy
    respond_to do |format|
      format.html { redirect_to cause_statuses_url, notice: 'Cause status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cause_status
      @cause_status = CauseStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cause_status_params
      params.require(:cause_status).permit(:cause_id, :attorney_id, :expiration_date, :finished,:description)
    end
end

app/helpers/cause_statuses_helper.rb
module CauseStatusesHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/cause_statuses/_form.html.erb
<%= form_with(model: cause_status, local: true) do |form| %>
  <% if cause_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cause_status.errors.count, "error") %> prohibited this cause_status from being saved:</h2>

      <ul>
      <% cause_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cause_id %>
    <%= form.text_field :cause_id %>
  </div>

  <div class="field">
    <%= form.label :attorney_id %>
    <%= form.text_field :attorney_id %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.datetime_select :expiration_date %>
  </div>

  <div class="field">
    <%= form.label :finished %>
    <%= form.check_box :finished %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cause_statuses/_new.html.erb
<div id="myModalCauseTareas" class="modal fade"  >
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Nuevo Estado</h4>
      </div>

      
        <%= form_for @cause_status, remote: true do |form| %>
        <div class="modal-body">
          <!-- Main content -->
          <section class="content">
            <div class="row">
              <div class="col-md-12">
                <div class="box box-primary">
              
                  <form role="form">
                    <div class="box-body">
                    <div class="alert alert-danger" role="alert" style="display: none;"></div>
                     
                      
              
                    <div class="form-group col-md-4">
                        <%= form.label :Causa %>
                        <%= form.select :cause_id, options_from_collection_for_select( Cause.all, :id, :name)  %>
                    </div>

                    <div class="form-group col-md-4">
                        <%= form.label :Abogado_a_cargo %>
                         <%= form.select :attorney_id, options_from_collection_for_select( Attorney.all, :id, :name)  %>
                       
                    </div>

                    <div class="form-group col-md-8">
                        <%= form.label :Descripcion %>
                        <%= form.text_field :description %>
                    </div>
                    <div class="form-group col-md-8">
                        <%= form.label :Fecha_de_termino %>
                        <%= form.datetime_select :expiration_date ,
                         {
                                  :order => [:day, :month, :year], 
                                  :value => DateTime.now.strftime('%m/%d/%Y')
                                }%>
                    </div>

                    

                      <div class="form-group col-md-4">
                         
                          <%= form.hidden_field :finished ,  :value => false %>
                      </div>

                      
                    </div>
                </div>
              </div>  <!-- /.box -->
                    <div class="modal-footer">
                        <%= form.submit "Guardar",class: "btn btn-primary btn-lg btn-block" %>
                    </div>
                  <% end %>
              </div>
              
          </div>
        </div>
      </div>

app/views/cause_statuses/create.js.erb
<% if @cause_status.errors.empty? %>
  $('#myModalCauseTareas').modal('hide');
<% else %>
  alert('<%= @cause_status.errors.full_messages[0] %>');
<% end %>

app/views/cause_statuses/edit.html.erb
<h1>Editing Cause Status</h1>

<%= render 'form', cause_status: @cause_status %>

<%= link_to 'Show', @cause_status %> |
<%= link_to 'Back', cause_statuses_path %>

app/views/cause_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cause Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Cause</th>
      <th>Attorney</th>
      <th>Expiration date</th>
      <th>Finished</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cause_statuses.each do |cause_status| %>
      <tr>
        <td><%= cause_status.cause %></td>
        <td><%= cause_status.attorney %></td>
        <td><%= cause_status.expiration_date %></td>
        <td><%= cause_status.finished %></td>
        <td><%= cause_status.description %></td>
        <td><%= link_to 'Show', cause_status %></td>
        <td><%= link_to 'Edit', edit_cause_status_path(cause_status) %></td>
        <td><%= link_to 'Destroy', cause_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cause Status', new_cause_status_path %>

app/views/cause_statuses/new.html.erb
<h1>New Cause Status</h1>

<%= render 'form', cause_status: @cause_status %>

<%= link_to 'Back', cause_statuses_path %>

app/views/cause_statuses/new.js.erb
$('<%= j render "new"%>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/cause_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cause:</strong>
  <%= @cause_status.cause %>
</p>

<p>
  <strong>Attorney:</strong>
  <%= @cause_status.attorney %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @cause_status.expiration_date %>
</p>

<p>
  <strong>Finished:</strong>
  <%= @cause_status.finished %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cause_status.description %>
</p>

<%= link_to 'Edit', edit_cause_status_path(@cause_status) %> |
<%= link_to 'Back', cause_statuses_path %>